version: '3.8'

services:
  web:
    build: ./url_shortener
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./url_shortener/:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "shortener", "-U", "shortener_user" ]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
